SPACESHIP_TIME_SHOW=true

SPACESHIP_BUN_SHOW=false
SPACESHIP_DENO_SHOW=false
SPACESHIP_DOCKER_COMPOSE_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_ELIXIR_SHOW=false
SPACESHIP_ERLANG_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_RUBY_SHOW=false
SPACESHIP_RUST_SHOW=false
SPACESHIP_TERRAFORM_SHOW=false
SPACESHIP_UV_SHOW=false
SPACESHIP_VENV_SHOW=false

# SPACESHIP_KUBECTL_SHOW=true
# SPACESHIP_KUBECTL_SYMBOL="󱃾"
SPACESHIP_KUBECTL_CONTEXT_COLOR_GROUPS=(
  red  'production'
  cyan 'staging' 
)
