#!/bin/bash

set -e

if [ "$1" != "" ]; then
  backup_dir="$1"
else
  backup_dir="../data/$(date +%Y-%m-%d)-$(basename "$(git rev-parse --show-toplevel)")"
  if [ -d "$backup_dir" ]; then 
    # Append current time in HH:MM:SS format
    backup_dir="${backup_dir}-$(date +%H:%M:%S)"
  else
    # create folder with the name of the repo prepended with the current date
    mkdir -p "$backup_dir"
  fi
fi


if [ -d .git ]; then
  # if there are any untracked files
  if [ "$(git ls-files --others --exclude-standard)" != "" ]; then
    # move untracked files to the folder
    while IFS= read -r file ; do
      mv "$file" "$backup_dir"
    done < <(git ls-files --others --exclude-standard)
    # stash any changes
    git stash
  fi
fi
