version: 2
log-file: /Users/leonid.batyuk/.cache/nvim/efm.log
log-level: 1

tools:
  sbs_credo: &sbs_credo
    # lint-command: "make dockerless dockerless=true cmd='MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}'"
    lint-command: "MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
    root-markers:
      - mix.lock
      - Makefile
      - docker-compose.yml

languages:
  elixir:
    - <<: *sbs_credo
