-- require("nvim-treesitter").install {
--   "bash",
--   "c",
--   "c_sharp", -- unity
--   "cmake",
--   "cpp",
--   "css",
--   "devicetree",
--   "dockerfile",
--   "eex",
--   "elixir",
--   "erlang",
--   "go",
--   "gomod",
--   "hcl",
--   "heex",
--   "html",
--   "http",
--   "java",
--   "json",
--   "latex",
--   "lua",
--   "make",
--   "markdown",
--   "markdown_inline",
--   "python",
--   "regex",
--   "ruby",
--   "rust",
--   "scss",
--   "surface",
--   "toml",
--   "typescript",
--   "vim",
--   "yaml",
--   "zig",
-- }
-- TODO figure out how to do this after the major update
--   incremental_selection = {
--     enable = true,
--     keymaps = {
--       init_selection = "gnn",
--       node_incremental = "grn",
--       scope_incremental = "grc",
--       node_decremental = "grm",
--     },
--   },
--   textobjects = {
--     move = {
--       enable = true,
--       set_jumps = true, -- whether to set jumps in the jumplist
--       goto_next_start = {
--         ["]m"] = "@function.outer",
--         ["]]"] = "@class.outer",
--       },
--       goto_next_end = {
--         ["]M"] = "@function.outer",
--         ["]["] = "@class.outer",
--       },
--       goto_previous_start = {
--         ["[m"] = "@function.outer",
--         ["[["] = "@class.outer",
--       },
--       goto_previous_end = {
--         ["[M"] = "@function.outer",
--         ["[]"] = "@class.outer",
--       },
--     },
--   },
-- })
